### ISSUE TITLE
밀집된 지역의 UI 표시 문제

### ISSUE THREAD

**Issue by yangroro** [codeforseoul/jonmat#1]
여의도같이 밀집되어있는 곳을 표시할때 UI가 겹치는 문제가 있습니다.

**Comment by lexifdev** [comment]
1. 클러스터를 활용하는 방법.
   https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/
2. 적절하게 필터를 적용해서 한번에 보여주는 수를 제한 하는 방법이 있을 듯 합니다.

어떤게 좋을까요?

**Comment by yangroro** [comment]
1. 클러스터를 활용하는 방법이 좀더 좋을 것 같습니다.
   필터를 사용해도 밀집되어있는 지역은 계속 나올것 같네요.

**Comment by incleaf** [comment]
오 저런 기능이 이미 있다면 구현하기는 어렵지 않겠네요!
그나저나 맵에 실제 정보가 부족해서 휑하다는 느낌이 들지 않으세요?
구글 맵 혹은 네이버 맵을 이용하는게 좋지 않을까 하는 의견입니다!
추후에 실제 식당과 인터렉티브한 작업을 할 때도 더 편할 것 같아서요

**Comment by lexifdev** [comment]
@incleaf 별도로 이슈 하나 만들어주세요.

**Comment by incleaf** [comment]
#2 에서 진행합니다

**Comment by lexifdev** [comment]
일감 넘기기 배틀!

**Comment by yangroro** [comment]
안타깝게도 제가 모바일 앱 개발자라 Web Frontend를 전혀 다루지 못합니다.

**Comment by lexifdev** [comment]
#2 작업에서 덩달아 해결이 되어서 이 이슈는 닫습니다.
