### ISSUE TITLE
지도 라이브러리 변경

### ISSUE THREAD

**Issue by incleaf** [codeforseoul/jonmat#2]
맵에 실제 정보가 부족해 휑하다는 느낌이 들어서, 구글 맵 혹은 네이버 맵을 이용하는게 좋을 것 같습니다.
추후에 실제 식당과 인터렉티브한 작업을 할 때도 더 편할 것 같네요~

**Comment by lexifdev** [comment]
방법은 
1. leaflet을 유지하고 tile만 openstreetmap 등으로 교체한다.
http://www.openstreetmap.org/node/357906447#map=17/37.52979/126.92310
2. 다음이나 구글등의 맵 제공자로 바꾼다.

두가지가 있을 듯 합니다.
 어떤 게 좋을까요

**Comment by incleaf** [comment]
구글 맵으로 포팅하는 작업 진행 해볼게요~ 완료 후에 슬랙에서 다 같이 어떤게 나을지 의논해봐요

**Comment by lexifdev** [comment]
@incleaf 변경된 내용 확인했습니다. 보기는 훨씬 예쁘네요 ㅎㅎㅎㅎ
코드 indent 만 맞추고(현재 기존 코드들은 space 4개) 기존에 안쓰게 된 파일들만 지워주시면 gh-pages로 머지 하겠습니다.
귀찮으시면 제가 해도 되구요.

**Comment by incleaf** [comment]
@lexifdev 아니에요 제가 해야죠! ㅋㅋ 수정 해서 다시 커밋 하겠습니다.

**Comment by incleaf** [comment]
@lexifdev  혹시 다음에 필요하지 않을까 싶어서 기존 파일은 그냥 두고 indent만 수정했어요!
저 처럼 기본 탭 크기가 2인 분들을 위해 `.editorconfig`도 추가해뒀어요.

**Comment by lexifdev** [comment]
@incleaf 머지해서 배포되었습니다. :+1:
