### ISSUE TITLE
같은 횟수일 경우 금액 내림차순으로 정렬

### ISSUE THREAD

**Issue by bek9** [codeforseoul/jonmat#7]
1회 방문이 70% 이상을 차지하고 있는 것 같은데 금액이 천차만별입니다.
 방문횟수 내림차순, 금액 내림차순 정렬이 필요합니다!

**Comment by lexifdev** [comment]
숫자가 적은 하위 몇 %는 생략해버리는 건 어떨까요?

**Comment by lexifdev** [comment]
정렬 순서 자체에는 찬성입니다.
