### ISSUE TITLE
식당 이름에 링크 추가

### ISSUE THREAD

**Issue by bek9** [codeforseoul/jonmat#9]
식당 이름에 다이닝 코드 같은 맛집 사이트 쿼리스트링 링크를 추가

**Comment by bek9** [comment]
의원님들이 다니시는 곳이라 안 나오는 곳도 많네요. 이름이 겹칠 경우 주소도 확인해 봐야 할 거 같고.. 잘만 되면 썸네일 사진 한장 가져오는 것도 될텐데

**Comment by hoony-o-1** [comment]
“의원님들이 다니시는 곳이라” ㅋㅋㅋ
